name: 'Deploy'

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install modules
        run: bun install --frozen-lockfile
      - name: Build next app
        run: bun run build
      - name: Setup git info
        run: |
          git config --global user.email 'rpmccarter@gmail.com'
          git config --global user.name 'Ronan McCarter'
      - name: Deploy to github pages
        run: bun run deploy
